# Generated by Django 4.1.3 on 2023-02-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookprog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='progress_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
