# Generated by Django 4.1.3 on 2023-02-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookprog', '0002_remove_book_id_remove_progress_id_book_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
    ]
